### ISSUE TITLE
Mistakes or missing code in Factify2-Baseline

### ISSUE THREAD

**Issue by ivana-13** [surya1701/Factify-2.0#3]
There are numerous mistakes in the code provided in the github, which prevent users from running the code. 

1. The test.csv file that is available for downloading does not contain Category column, which means that no function for datasets (create_dataset or dataloader) works for this split.
2. There is a code 
`vis_model = BertViT(device, 5)` 
which is not initialized or imported anywhere in the code and I was not able to find such a model in transformers library.

Could you elaborate on this and provide explanation or improve the code?
Thank you

**Comment by Shreyashm16** [comment]
1. We have intentionally removed the labels from the test data to maintain the integrity of the competition. One can request access to the test labels through email.
2. We have added the definition for BertViT.
